### ISSUE TITLE
New version of virtualenv breaks inenv

### ISSUE THREAD

**Issue by ljades** [pnegahdar/inenv#49]
As of `virtualenv==20.0.0`, inenv is now broken, as line 11 in venvy.py:

```from virtualenv import path_locations```

is deprecated.

`virtualenv` needs to be capped at `<20.0.0` for this to work, or for the functionality around virtualenv to change.

I have a PR ready to be made but would need to be a contributor to push the branch.

**Comment by pnegahdar** [comment]
Invite sent.

**Comment by ljades** [comment]
Latest version fixed it, thanks!
